config/routes.rb
Rails.application.routes.draw do

  resources :boards do
    resources :initiatives
    resources :teams
    resources :roles
    resources :projects
    resources :locations
    resources :people do
      collection do
        get :autocomplete
      end
    end
    get 'changelog'
    get 'allocation'
    get 'completed'
    get 'todo'
    post 'send_reminders'
    get 'search', to: 'search#search'
    get 'search/index', to: 'search#index'

  end

  resources :initiatives do
    resources :projects
  end

  resources :projects do
    resources :project_members
  end

  resources :people do
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'home/index'

  get 'sessions/create'

  get '/auth/:provider/callback', to: 'sessions#create'

  authenticated :user do
    devise_scope :user do
      root to: "boards#index"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "home#index", :as => "unauthenticated"
    end
  end

end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  belongs_to :manager, class_name: "Person"
  belongs_to :analyst, class_name: "Person"
  belongs_to :owner, class_name: "Person"
  belongs_to :security, class_name: "Person"
  has_many :projects
  belongs_to :board

  validates :name, presence: { message: "Please specify a name"}
  validates :board_id, presence: true

  has_paper_trail :meta => { :board_id  => :board_id }

  def ongoing_projects
    self.projects.where.not(completed: true).order(:start_date, created_at: :asc)
  end
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board
  before_action :set_initiative, only: [:show, :edit, :update, :destroy]
  before_action :set_select_fields, only: [:new, :edit, :update]

  # GET /initiatives
  # GET /initiatives.json
  def index
    @initiatives = Initiative.where(:board_id => @board.id)
  end

  # GET /initiatives/1
  # GET /initiatives/1.json
  def show
  end

  # GET /initiatives/new
  def new
    @initiative = @board.initiatives.build
  end

  # GET /initiatives/1/edit
  def edit
  end

  # POST /initiatives
  # POST /initiatives.json
  def create
    @initiative = @board.initiatives.build(initiative_params)

    respond_to do |format|
      if @initiative.save
        format.html { redirect_to board_url(@board), notice: @initiative.name + ' Initiative was successfully created.' }
        format.json { render :show, status: :created, location: @initiative }
      else
        format.html { render :new }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /initiatives/1
  # PATCH/PUT /initiatives/1.json
  def update
    respond_to do |format|
      if @initiative.update(initiative_params)
        format.html { redirect_to board_url(@board), notice: @initiative.name + ' Initiative was successfully updated.' }
        format.json { render :show, status: :ok, location: @initiative }
      else
        format.html { render :edit }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initiatives/1
  # DELETE /initiatives/1.json
  def destroy
    @initiative.destroy
    respond_to do |format|
      format.html { redirect_to edit_board_initiative_path(@board) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_initiative
      @initiative = Initiative.find(params[:id])
    end

    def set_board
      @board = Board.find(params[:board_id])
      @show_boards_nav = !@board.nil? && !@board.new_record?
    end

    def set_select_fields
      @people = Person.where(board_id: @board.id).order(:name)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def initiative_params
      if (params[:ended]) 
        params[:end_date] = today
      end
      params.require(:initiative).permit(:name, :start_date, :end_date, :manager_id, :analyst_id, :owner_id, :security_id, :board_id, :completed, :standing)
    end
end

app/views/initiatives/_form.html.erb
<%= bootstrap_form_for([@board, @initiative], :layout => :horizontal, label_col: "col-md-1", control_col: "col-md-4") do |f| %>
  <% if @initiative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@initiative.errors.count, "error") %> prohibited this initiative from being saved:</h2>

      <ul>
      <% @initiative.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name %>
  <%= f.date_field :start_date %>
  <%= f.date_field :end_date %>
  <%= f.collection_select :manager_id, @people, :id, :name, { :include_blank => true } %>
  <%= f.collection_select :analyst_id, @people, :id, :name, { :include_blank => true } %>
  <%= f.collection_select :owner_id, @people, :id, :name, { :include_blank => true } %>
  <%= f.collection_select :security_id, @people, :id, :name, { :include_blank => true } %>

  <div class="form-group">
    <div class="col-md-5 col-md-offset-1">
      <%= f.check_box :standing %>
      <p class="help-block">This is the Initiative that never ends</p>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-5 col-md-offset-1">
      <%= f.check_box :completed %>
    </div>
  </div>

  <div class="actions form-group">
    <%= f.hidden_field :board_id, :value => @board.id %>
    <%= f.primary %> <%= link_to 'Cancel', board_path(@board), :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/initiatives/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Manager</th>
      <th>Analyst</th>
      <th>Owner</th>
      <th>Completed?</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% initiatives.each do |initiative| %>
      <tr>
        <td><%= link_to initiative.name, edit_board_initiative_path(@board, initiative) %></td>
        <td><%= initiative.start_date %></td>
        <td><%= initiative.end_date %></td>
        <td><%= initiative.manager ? initiative.manager.name : '' %></td>
        <td><%= initiative.analyst ? initiative.analyst.name : '' %></td>
        <td><%= initiative.owner ? initiative.owner.name : '' %></td>
        <td><%= initiative.completed? ? 'Yes' : 'No' %></td>
        <td><%= link_to 'Destroy', board_initiative_url(@board, initiative), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/initiatives/edit.html.erb
<% @title = "#{@initiative.name} Initiative" %>
<h1>Edit Initiative</h1>
<%= render 'form' %>

<div class="row">
  <h2>Initiative Projects</h2>
  <div class="col-md-12">
    <table class="table">
      <tr>
        <th>Project</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Completed?</th>
      </tr>
    <% @initiative.projects.each do |p| %>
      <tr>
        <td><%= link_to p.name, edit_board_project_path(@board, p) %></td>
        <td><%= p.start_date %></td>
        <td><%= p.end_date %></td>
        <td><%= p.completed? ? 'Yes' : 'No' %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/initiatives/index.html.erb
<% @title = "Initiatives for #{@board.name}" %>
<h1>Initiatives <span><%= link_to 'Create New', new_board_initiative_path(@board), :class => 'btn btn-primary btn-xs' %></h1>

<%= render partial: "initiatives/table", locals: {initiatives: @initiatives} %>

app/views/initiatives/new.html.erb
<% @title = "New Initiative for #{@board.name}" %>
<h1>New initiative</h1>

<%= render 'form' %>

<%= link_to 'Back', initiatives_path %>

app/views/initiatives/show.html.erb
<% @title = "#{@initiative.name} Initiative" %>
<div class="row">
  <p>
    <strong>Name:</strong>
    <%= @initiative.name %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= @initiative.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= @initiative.end_date %>
  </p>

  <p>
    <strong>Manager:</strong>
    <%= @initiative.manager.name unless @initiative.manager.nil? %>
  </p>

  <p>
    <strong>Analyst:</strong>
    <%= @initiative.analyst.name unless @initiative.analyst.nil? %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= @initiative.owner.name unless @initiative.owner.nil? %>
  </p>

  <p>
    <strong>Security:</strong>
    <%= @initiative.security.name unless @initiative.security.nil? %>
  </p>

  <p>
    <%= link_to 'Edit', edit_board_initiative_path(@board, @initiative) %> |
    <%= link_to 'Back', board_initiatives_path(@board) %>
  </p>
</div>