config/routes.rb
Rails.application.routes.draw do

  resources :boards do
    resources :initiatives
    resources :teams
    resources :roles
    resources :projects
    resources :locations
    resources :people do
      collection do
        get :autocomplete
      end
    end
    get 'changelog'
    get 'allocation'
    get 'completed'
    get 'todo'
    post 'send_reminders'
    get 'search', to: 'search#search'
    get 'search/index', to: 'search#index'

  end

  resources :initiatives do
    resources :projects
  end

  resources :projects do
    resources :project_members
  end

  resources :people do
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'home/index'

  get 'sessions/create'

  get '/auth/:provider/callback', to: 'sessions#create'

  authenticated :user do
    devise_scope :user do
      root to: "boards#index"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "home#index", :as => "unauthenticated"
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_paper_trail :meta => { :board_id  => :board_identifier }, :ignore => [:notes, :updated_at]

  belongs_to :initiative
  belongs_to :location
  has_many :project_members, :dependent => :destroy
  has_many :members, :through => :project_members, :source => :person

  validates_presence_of :name, :initiative_id, :location, :project_description
  validates_presence_of :product_spec, :yammer_group, :if => :not_standing?

  def board_identifier
    self.initiative.board.id
  end

  def active_project_members_for_role role_id
    self.project_members.where("role_id = ? AND (end_date >= ? OR end_date IS NULL)", role_id, Date.today).order(:start_date)
  end

  def vacation?
    self.name == "Vacation"
  end

  def not_standing?
    !self.initiative.standing?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only: [:create, :show, :new, :edit, :update]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    initiative = Initiative.find_by_id(project_params[:initiative_id])
    if initiative.nil?
      @project = Project.new(project_params)
    else
      @project = initiative.projects.build(project_params)
    end

    respond_to do |format|
      if @project.save
        if @project.start_date
          post_new_project_to_yammer
        end
        format.html { redirect_to @board, notice: @project.name + ' was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        update_dates if !@project.initiative.standing?
        format.html { redirect_to @board, notice: @project.name + ' was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_board
      @board = Board.find(params[:board_id])
      @initiatives = @board.ongoing_initiatives
      @show_boards_nav = !@board.nil? && !@board.new_record?
    end

    def update_dates
      #if project start date changes, then change the start dates for the people
      if @project.previous_changes.has_key? "start_date"
        @project.project_members.each do |pm|
          pm.update_attributes(:start_date => @project.start_date)
        end
      end
      #if project end date changes, then change the end dates for the people
      if @project.previous_changes.has_key? "end_date"
        @project.project_members.each do |pm|
          pm.update_attributes(:end_date => @project.end_date)
        end
      end
      #if project has a start date now but previously did not, then post to yammer about a new project starting
      if @project.previous_changes.has_key?("start_date") && @project.previous_changes["start_date"][0].nil?
        post_new_project_to_yammer
      end
    end

    def post_new_project_to_yammer
      #only post to yammer if it's a Product or Internal Project
      if !["Support/Other"].include?(@project.project_type) && @board.id && !@project.initiative.standing?
        #if project gets a start date and start date was previously nil, then post to yammer about a new project
        yamr = Yammer::Client.new(:access_token  => current_user.access_token)
        permalinks_to_alert = []
        people_to_alert = Person.where(:new_project_alert => [@project.project_type, "All"], :board => @board).where.not(:permalink => nil)
        people_to_alert.each do |p|
          permalinks_to_alert.push("@"+p.permalink) if !p.new_project_alert.blank?
        end

        yamr.create_message("A new project called '" + @project.name + "' in the " + @project.initiative.name + " initiative has been \
          added to the bigboard with a kickoff date of " + @project.start_date.strftime("%B %d, %Y") + ". Go check it out! " + edit_board_project_url(@board, @project) + " \n\n Courtesy \
          mentions: " + permalinks_to_alert.join(", "), :group_id => @board.group_id_for_yammer_post)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :start_date, :end_date, :completed, :retro, :status, :location, :location_id, :project_type, :initiative_id, :board_id, :notes, :tech_spec, :product_spec, :retrospective, :yammer_group, :experiment_key, :project_description)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
 <script type="text/javascript">
  function hideStanding() {
    standing = $("#project_initiative_id").find(":selected").attr("data-standing")

      elements = $(".not-standing-field")

      for (i = 0; i < elements.length ; i++){
        if (standing == "true") {
          $(elements[i]).hide()
          $(elements[i]).find("input").val("")
        } else {
          $(elements[i]).show()
        }
      }
  }
</script>
  <style>
  .hide-standing {
    display :none;
  }
</style>
<div class="row">
  <div class="col-md-6">
    <%= bootstrap_form_for([@board, @project], layout: :horizontal, label_col: "col-md-3", control_col: "col-md-6") do |f| %>
      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.text_field :name, :label => "Name*" %>
      </div>
      <div>
      <%= f.select :initiative_id, options_for_select(@initiatives.map{ |i| [i.name, i.id, {'data-standing'=>i.standing}] }, @project.initiative.try(:id) ), :label => "Initiative*", :onchange => "hideStanding()"%>
      </div>
      <div class="field">
        <%= f.text_area :project_description, :label => "Project description*", :rows => 5 %>
      </div>
      <div class="field not-standing-field <%= @project.initiative.present? && @project.initiative.standing ? 'hide-standing' : '' %>">
        <%= f.text_field :product_spec, :label => "Product spec*" %>
      </div>
      <div class="field not-standing-field <%= @project.initiative.present? && @project.initiative.standing ? 'hide-standing' : '' %>">
        <%= f.text_field :tech_spec %>
      </div>
      <div class="field not-standing-field <%= @project.initiative.present? && @project.initiative.standing ? 'hide-standing' : '' %>">
        <%= f.text_field :yammer_group, :label => "Yammer group link*" %>
      </div>
      <div class="field not-standing-field <%= @project.initiative.present? && @project.initiative.standing ? 'hide-standing' : '' %>">
        <%= f.text_field :experiment_key, placeholder: 'Enter "none" if project has no experiment' %>
      </div>
      <div class="field">
        <%= f.date_field :start_date %>
      </div>
      <%= f.date_field :end_date %>
      <%= f.collection_select :location_id, @board.locations, :id, :name, :include_blank => true %>
      <%= f.select :project_type, ['', 'Product', 'Internal Projects', 'Support/Other'] %>
      <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
          <%= f.check_box :completed %>
        </div>
      </div>
      <div class="field not-standing-field <%= @project.initiative.present? && @project.initiative.standing ? 'hide-standing' : '' %>">
        <%= f.text_field :retrospective %>
      </div>
      <div class="form-group">
        <div class="col-md-offset-3 col-md-6">
          <%= f.submit %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
  <h3>Project Members</h3>
  <% unless @project.project_members.nil? %>
  <ul class="project-members-list">
  <% @project.project_members.order(role_id: :asc).each do |pm| %>
    <li>
      <%= person_tag pm %> (<%= pm.role.name %>)
      <%= link_to 'Delete', project_project_member_path(@project, pm), method: :delete, :class => 'btn btn-danger btn-xs', data: { :confirm => 'Are you sure you want to delete?' } %>
    </li>
  <% end %>
  </ul>
  <% end %>
  <h3>Changelog</h3>
  <ul>
  <% @project.versions.each do |v| %>
    <li>
      <% if v.changeset.empty? %>
      <%= v.event %> on <%= v.created_at.strftime("%m/%d/%y") %>
      <% else %>
      <%= Project.human_attribute_name(v.changeset.first[0]) %> changed: <strong><%= v.changeset.first[1].join(' → ') %></strong>
      <% end %>
      by <%= User.find_by_id(v.whodunnit).name unless User.find_by_id(v.whodunnit).nil? %>
      on <%= v.created_at.strftime("%m/%d/%y") %>
    </li>
  <% end %>
  <% @project.project_members.each do |pm| %>
    <% pm.versions.each do |v| %>
    <% if v.event == 'create' %>
      <li class="project-changelog-list">
        <%= person_tag pm %> added
        by <%= User.find_by_id(v.whodunnit).name unless User.find_by_id(v.whodunnit).nil? %>
      on <%= v.created_at.strftime("%m/%d/%y") %>
      </li>
      <% end %>
    <% end %>
  <% end %>
  </ul>
  </div>
</div>

app/views/projects/edit.html.erb
<%= render partial: "teams/css", locals: {teams: @board.teams} %>
<% @title = "#{@project.name} Project" %>

<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Back', @board %>

app/views/projects/index.html.erb
<% @title = "#{@board.name} Projects" %>
<h1 class="page-header">Projects <span><%= link_to 'Create New', new_project_path, :class => 'btn btn-primary btn-xs' %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
      <th>Location</th>
      <th>Type</th>
      <th>Initiative</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, edit_project_path(project) %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td><%= project.status %></td>
        <td><%= project.location %></td>
        <td><%= project.project_type %></td>
        <td><%= project.initiative ? project.initiative.name : '' %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<% @title = "New #{@board.name} Project" %>
<h1>New project</h1>

<% if @initiatives.size < 1 %>
  <div class="alert alert-danger fade in">
    <strong>No Initiatives found.</strong> You must <%= link_to "create an Initiative", new_board_initiative_path(@board) %> before you can add projects. 
  </div>
<% else %>
<%= render 'form' %>
<% end %>

<%= link_to 'Back', @board, :class => 'btn btn-default' %>

app/views/projects/show.html.erb
<% @title = "#{@project.name} Project" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>End Date:</strong>
  <%= @project.end_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<p>
  <strong>Location:</strong>
  <%= @project.location %>
</p>

<p>
  <strong>Type:</strong>
  <%= @project.project_type %>
</p>

<p>
  <strong>Initiative:</strong>
  <%= @project.initiative.name %>
</p>

<%= link_to 'Edit', edit_board_project_path(@board, @project) %> |
<%= link_to 'Back', projects_path %>