config/routes.rb
Rails.application.routes.draw do

  resources :boards do
    resources :initiatives
    resources :teams
    resources :roles
    resources :projects
    resources :locations
    resources :people do
      collection do
        get :autocomplete
      end
    end
    get 'changelog'
    get 'allocation'
    get 'completed'
    get 'todo'
    post 'send_reminders'
    get 'search', to: 'search#search'
    get 'search/index', to: 'search#index'

  end

  resources :initiatives do
    resources :projects
  end

  resources :projects do
    resources :project_members
  end

  resources :people do
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'home/index'

  get 'sessions/create'

  get '/auth/:provider/callback', to: 'sessions#create'

  authenticated :user do
    devise_scope :user do
      root to: "boards#index"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "home#index", :as => "unauthenticated"
    end
  end

end

app/models/board.rb
require 'yammer'
include ApplicationHelper

class Board < ActiveRecord::Base
  has_paper_trail :meta => { :board_id  => :id }

  belongs_to :user
  belongs_to :network
  has_many :initiatives, :dependent => :destroy
  has_many :teams, :dependent => :destroy
  has_many :roles, :dependent => :destroy
  has_many :people, :dependent => :destroy
  has_many :locations, :dependent => :destroy
  has_many :projects, :through => :initiatives

  validates :network_id, presence: { message: "Is user logged in?"}
  validates :name, presence: { message: "Please specify a name"}

  def ongoing_initiatives
      self.initiatives.where(completed: false).order(:created_at)
  end

  def people_ending_soon
    @people_ending_soon = []
    self.people.each do |p|
      if (p.project_members.count == 1 && p.project_members[0].end_date)
        if p.freeing_up_soon? && p.team.single_project?
          project_hash = { "person_name" => p.name,
           "project_end_date" => p.project_members[0].end_date,
           "project_name" => p.project_members[0].project.name
         }
          @people_ending_soon << project_hash
        end
      end
    end
    @people_ending_soon
  end

  def search(experiment_key)
    self.projects.where(:experiment_key => experiment_key)
  end

  def long_projects(location_name)
    self.projects.where(:completed => false).where.not(:location_id => nil).order(:start_date).select { |cp|
      !cp.initiative.standing? && num_weeks(cp.start_date, Date.today) >= 5 && cp.location.name == location_name
    }
  end

  def recent_projects(location_name)
    self.projects.where(:completed => false).where.not(:location_id => nil).order(:start_date).select { |cp|
      !cp.initiative.standing? && cp.start_date && num_weeks(cp.start_date, Date.today) <= 3 && cp.location.name == location_name
    }
  end

  def has_long_projects
    self.locations.each do |l|
      if long_projects(l.name) != []
        return true
      end
    end
    return false
  end

    def has_recent_projects
    self.locations.each do |l|
      if recent_projects(l.name) != []
        return true
      end
    end
    return false
  end


end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user_from_token!
  before_action :authenticate_user!
  before_action :set_board, only: [:show, :edit, :changelog, :allocation, :completed, :update, :destroy, :todo, :send_reminders]

  # GET /boards
  # GET /boards.json
  def index

    respond_to do |format|
      format.html { @boards = Board.where network_id: current_user.network_id }
      format.json { @boards = Board.where network_id: current_user.network_id }

    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)
    @board.network_id = current_user.network_id
    @board.user = current_user

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end

  def allocation
    @teams = @board.teams.where(:single_project => true).order(:name)
    @initiatives = @board.initiatives.where(:completed => false)
    @allocations = {}
    @allocations[:total] = 0

    @initiatives.each do |i|
      @allocations[i] = {}
      @allocations[i][:total] = 0
      @allocations[i][:people] = {}
      @teams.each do |t|
        @allocations[i][:people][t] = []
      end
    end

    @teams.each do |t|
      t.people.each do |p|
        if p.active_project_count != 0
          person_initiative = p.active_projects.first.initiative
          if !person_initiative.completed
            @allocations[:total] += 1
            @allocations[person_initiative][:total] += 1
            @allocations[person_initiative][:people][t].push(p)
          end
        end
      end
    end

    # group together product initiatives
    @allocations_product_bucket = {}
    @allocations_product_bucket[:total] = 0
    @allocations_product_bucket[:product] = {}

    # create data for pie charts
    @allocations_product_pie = {}
    @allocations_supeng_pie = {}

    #set up hashes
    @initiatives.each do |i|
      if product_initiative?(i)
        @allocations_product_bucket[:product][:total] = 0
        @allocations_product_bucket[:product][:people] = {}
        @allocations_product_pie[i.name] = 0
        @teams.each do |t|
          @allocations_product_bucket[:product][:people][t] = []
        end
      else
        @allocations_product_bucket[i] = {}
        @allocations_product_bucket[i][:total] = 0
        @allocations_product_bucket[i][:people] = {}
        @teams.each do |t|
          @allocations_product_bucket[i][:people][t] = []
          @allocations_supeng_pie[t.name] = 0
        end
      end
    end

    # populate hashes with data
    @teams.each do |t|
      t.people.each do |p|
        if p.active_project_count != 0
          person_initiative = p.active_projects.first.initiative
          if !person_initiative.completed
            @allocations_product_bucket[:total] += 1
            if product_initiative?(person_initiative)
              @allocations_product_bucket[:product][:total] += 1
              @allocations_product_bucket[:product][:people][t].push(p)
              @allocations_product_pie[person_initiative.name] += 1
            else
              @allocations_product_bucket[person_initiative][:total] += 1
              @allocations_product_bucket[person_initiative][:people][t].push(p)
              @allocations_supeng_pie[t.name] += 1
            end
          end
        end
      end
    end

    @pie_all = allocations_pie_by_location("", @initiatives, @teams)
    @pie_sf = allocations_pie_by_location("SF", @initiatives, @teams)
    @pie_uk = allocations_pie_by_location("UK", @initiatives, @teams)
    @pie_red = allocations_pie_by_location("RED", @initiatives, @teams)
    @supeng_pie_all = supeng_pie_by_location("", @initiatives, @teams)
    @supeng_pie_sf = supeng_pie_by_location("SF", @initiatives, @teams)
    @supeng_pie_uk = supeng_pie_by_location("UK", @initiatives, @teams)
    @supeng_pie_red = supeng_pie_by_location("RED", @initiatives, @teams)

  end

  # GET /boards/1/changelog
  def changelog
    @versions = PaperTrail::Version.where(:board_id => @board.id).order(created_at: :desc)
  end

  # GET /boards/1/completed
  def completed
    @projects = [] # list of completed projects from non-standing initiatives, i.e. REAL projects
    @board.initiatives.where(:standing => false).each do |i|
      i.projects.where(:completed => true).where.not(:end_date => nil).each do |p|
        @projects.push(p)
    end
    end
  end

  # GET /boards/1/todo
  def todo
    @todo_projects = [] # list of projects missing experiment_key or tech_spec
    @board.initiatives.where(:standing => false).each do |i|
      i.projects.where(:experiment_key => [nil, ""], :tech_spec => [nil, ""]).where(:completed => false).each do |p|
        @todo_projects.push(p)
      end
    end
  end

  def send_reminders
    post_reminder_post_to_yammer(params[:data])

    flash[:notice] = "Reminders posted to Yammer"
    redirect_to board_todo_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      board = Board.find(params[:id] || params[:board_id])
      if board.network_id == current_user.network_id
        @board = board
      end
      @show_boards_nav = !@board.nil? && !@board.new_record?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:network_id, :name, :group_id_for_yammer_post)
    end

    def authenticate_user_from_token!
      user_email = params[:user_email].presence
      user       = user_email && User.find_by_email(user_email)

      # Notice how we use Devise.secure_compare to compare the token
      # in the database with the token given in the params, mitigating
      # timing attacks.
      if user && Devise.secure_compare(user.encrypted_password, params[:token])
        sign_in user, store: false
      end
    end

    def allocations_pie_by_location(location, initiatives, teams)
      @pie_data = {}

      initiatives.each do |i|
        if product_initiative?(i)
          @pie_data["Product"] = 0
        else
          @pie_data[i.name] = 0
        end
      end

      @teams.each do |t|
        t.people.each do |p|
          if p.active_project_count != 0
            person_initiative = p.active_projects.first.initiative
            if !person_initiative.completed
              if product_initiative?(person_initiative)
                @pie_data["Product"] += 1 if [p.location.name, ""].include?(location)
              else
                @pie_data[person_initiative.name] += 1 if [p.location.name, ""].include?(location)
              end
            end
          end
        end
      end
      return @pie_data
    end

    def supeng_pie_by_location(location, initiatives, teams)
      @pie_data = {}

      @teams.each do |t|
        @pie_data[t.name] = 0
        t.people.each do |p|
          if p.active_project_count != 0
            if p.active_projects.first.initiative.name == "Support Engineering"
              @pie_data[t.name] += 1 if [p.location.name, ""].include?(location)
            end
          end
        end
      end
      return @pie_data
    end

    def post_reminder_post_to_yammer(todo_project_ids)
      yamr = Yammer::Client.new(:access_token  => current_user.access_token)
      message = []
      todo_project_ids[0,3].each do |project_id|
        project = Project.find(project_id)
        if !project.initiative.standing?
          if project_group_id(project) # post to group if project has group link
            yamr.create_message("The project associated with this group has data missing on the big board (like experiment_key and tech spec link). Can you help us fill in the details? " + edit_board_project_url(@board, project), :group_id => project_group_id(project))
          else
            message << "\n\n" + project.name + ": " + edit_board_project_url(@board, project)
          end
        end
      end

      if @board.group_id_for_yammer_post and message.count != 0
        yamr.create_message("These projects have data missing on the big board (like experiment_key and tech spec link). Can you help us fill in the details? " + message.join, :group_id => @board.group_id_for_yammer_post)
      end
    end

    def project_group_id(project)
      return nil if project.yammer_group.nil? || project.yammer_group.match(/\&feedId=(.+)$/).nil?
      project.yammer_group.match(/\&feedId=(.+)$/)[1].to_i
    end
end

app/helpers/boards_helper.rb
module BoardsHelper

  def display_percentage num, den
    if num == 0
      "0"
    else
      per = percentage num, den
      "#{per}% (#{num})"
    end
  end

  def percentage num, den
    den == 0 ? 0 : (100*num.to_f/den.to_f).round(0)
  end

  def active_project person
    if person.active_project_count == 0
      "unassigned"
    else
      project = person.active_projects.first
      link_to project.name, board_project_path(project.initiative.board, project) unless project.nil?
    end
  end

  def version_object_link board, version
    link = ''
    name = ''
    if version.item_type == 'Project'
      item = Project.find_by_id version.item_id
      name = item.nil? ? '' : item.name
      link = link_to name, board_project_path(board, item) unless item.nil?
    elsif version.item_type == 'ProjectMember'
      item = ProjectMember.find_by_id version.item_id
      name = item.nil? || item.person.nil? ? '': item.person.name
      link = link_to name, project_project_member_path(item.project, item) unless item.nil?
    elsif version.item_type == 'Initiative'
      item = Initiative.find_by_id version.item_id
      name = item.nil? ? '' : item.name
      link = link_to name, board_initiative_path(board, item) unless item.nil?
    elsif version.item_type == 'Person'
      item = Person.find_by_id version.item_id
      name = item.nil? ? '' : item.name
      link = link_to name, board_person_path(board, item) unless item.nil?
    elsif version.item_type == 'Team'
      item = Team.find_by_id version.item_id
      name = item.nil? ? '' : item.name
      link = link_to name, board_team_path(board, item) unless item.nil?
    elsif version.item_type == 'Board'
      item = Board.find_by_id version.item_id
      name = item.nil? ? '' : item.name
      link = link_to name, board_team_path(board, item) unless item.nil?
    end
    link
  end

  def tl_projects
    #this only works for yammer bigboard because we have concept of TL
    #role_id => 4 is for TL
    tlProjects = []
    ProjectMember.where(:role_id => 4).order(:created_at).each do |pr| 
      if (pr.start_date and pr.start_date < Date.today and !pr.project.completed and !pr.project.initiative.standing and pr.person.location_old == "SF")
        tlProjects << pr.person.name + ": " +  pr.project.name 
      end
    end
    return tlProjects
  end

end

app/views/boards/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= bootstrap_form_for(@board, layout: :inline) do |f| %>
      <% if @board.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

          <ul>
          <% @board.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <%= f.text_field :group_id_for_yammer_post %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/boards/_validations.html.erb
<% @board.people.each do |p| %>
  <% if p.team.single_project? && p.active_project_count != 1 && !p.on_standing_initiative? && !p.initiative_owner? && !p.on_vacation? %>
  <div class="alert alert-warning"><%= link_to p.name, board_person_url(@board, p) %>
    <% if p.active_project_count == 0 %>
      <!-- person is not on the board at all -->
      <% if p.projects.count == 0 %>
        is unassigned
      <% elsif p.projects.count == 1 %>
        <% proj = p.projects[0] %>
        <% if (!proj.start_date || proj.start_date > Date.today) %>
          is only on project "<%= link_to proj.name, edit_board_project_path(@board, proj) %>" which hasn't started yet
        <% elsif proj.vacation? %>
          is unassigned (vacation soon)
        <% end %>
      <% else %>
        is !?!?!
      <% end %>
    <% elsif p.active_project_count > 1 %>
    is assigned to <%= p.active_project_count %> projects
    <% p.active_projects.each do |p| %>
    - <%= link_to p.name, edit_board_project_path(@board, p) %>
    <% end %>
  <% end %>
  </div>
  <% end %>
<% end %>
<% if @board.people_ending_soon != [] %>
<div class="alert alert-warning"> <b>People ending soon</b><br/>
  <% @board.people_ending_soon.each do |pes| %>
  - <%= pes["person_name"] %> ending on <%= pes["project_end_date"] %> (<%= pes["project_name"] %>)<br/>
  <% end %>
<% end %>
</div>

<% if @board.has_long_projects %>
  <div class="alert alert-warning"> <b>Long running projects</b><br/>
  <% @board.locations.each do |l| %>
   <%= l.name %><br/>
    <% @board.long_projects(l.name).each do |p| %>
      -- <%= link_to p.name, edit_board_project_path(@board, p) %> has been running for <%= num_weeks(p.start_date, Date.today) %> weeks<%= " (no end date)" if p.end_date == nil %>. <br/>
    <% end %>
  <% end %>
  </div>
<% end %>

<% if @board.has_recent_projects %>
  <div class="alert alert-warning"> <b>Recently staffed projects</b><br/>
  <% @board.locations.each do |l| %>
   <%= l.name %><br/>
    <% @board.recent_projects(l.name).each do |p| %>
      -- <%= link_to p.name, edit_board_project_path(@board, p) %> has been running for <%= num_weeks(p.start_date, Date.today) %> weeks. <br/>
    <% end %>
  <% end %>
  </div>
<% end %>

</div>

app/views/boards/allocation.html.erb
<h1>Project Allocation</h1>

<table class="table table-grid">
  <thead>
    <tr>
      <th>Type</th>
<% @teams.each do |t| %>
      <th><%= link_to t.name, board_team_path(@board, t) %></th>
<% end %>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
<% @board.initiatives.where(:completed => false).each do |i| %>
<% if !product_initiative?(i) %>
    <tr>
      <td><%= i.name %></td>
<% @teams.each do |t| %>
      <td title="<%= @allocations[i][:people][t].collect {|x| x.name} %>"><%= display_percentage @allocations[i][:people][t].size, t.people.size %>
      </td>
<% end %>
      <td><%= display_percentage @allocations[i][:total], @allocations[:total] %></td>
    </tr>
    <tr>
 <% end %>
    <tr>
<% end %>
<% @board.initiatives.where(:completed => false).each do |i| %>
<% if product_initiative?(i) %>
    <tr>
      <td><%= i.name %></td>
<% @teams.each do |t| %>
      <td title="<%= @allocations[i][:people][t].collect {|x| x.name} %>"><%= display_percentage @allocations[i][:people][t].size, t.people.size %>
      </td>
<% end %>
      <td><%= display_percentage @allocations[i][:total], @allocations[:total] %></td>
    </tr>
    <tr>
 <% end %>
    <tr>
<% end %>
      <th>Total</th>
<% @teams.each do |t| %>
      <td><%= t.people.size %></td>
<% end %>
      <td><%= @allocations[:total] %></td>
    </tr>
  </tbody>
</table>


<h1>Project Allocation with Product grouped together</h1>

<table class="table table-grid">
  <thead>
    <tr>
      <th>Type</th>
<% @teams.each do |t| %>
      <th><%= link_to t.name, board_team_path(@board, t) %></th>
<% end %>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
<% @board.initiatives.where(:completed => false).each do |i| %>
<% if !product_initiative?(i) %>
  <tr>
      <td><%= i.name %></td>
<% @teams.each do |t| %>
      <td title="<%= @allocations_product_bucket[i][:people][t].collect {|x| x.name} %>"><%= display_percentage @allocations_product_bucket[i][:people][t].size, t.people.size %>
      </td>
<% end %>
      <td><%= display_percentage @allocations_product_bucket[i][:total], @allocations_product_bucket[:total] %></td>
    </tr>
 <% end %>
 <% end %>
     <tr>
      <td> Product </td>
<% @teams.each do |t| %>
      <td title="<%= @allocations_product_bucket[:product][:people][t].collect {|x| x.name} %>"><%= display_percentage @allocations_product_bucket[:product][:people][t].size, t.people.size %>
      </td>
<% end %>
      <td><%= display_percentage @allocations_product_bucket[:product][:total], @allocations_product_bucket[:total] %></td>
    </tr>
    <tr>
      <th>Total</th>
<% @teams.each do |t| %>
      <td><%= t.people.size %></td>
<% end %>
      <td><%= @allocations_product_bucket[:total] %></td>
    </tr>
  </tbody>
</table>

<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<div class="pie-row">
  <h2>Bucket breakdown</h2>
  <div class="pie-container">TOTAL<%= pie_chart(@pie_all, height: "200px") %></div>
  <div class="pie-container">SF<%= pie_chart(@pie_sf, height: "200px") %></div>
  <div class="pie-container">UK<%= pie_chart(@pie_uk, height: "200px") %></div>
  <div class="pie-container">RED<%= pie_chart(@pie_red, height: "200px") %></div>
</div>

<div class="pie-row">
<h2>Product initiatives breakdown</h2>
<%= pie_chart(@allocations_product_pie) %>
</div>

<div class="pie-row">
<h2>Supeng breakdown by functional team</h2>
  <div class="pie-container">TOTAL<%= pie_chart(@supeng_pie_all, height: "200px") %></div>
  <div class="pie-container">SF<%= pie_chart(@supeng_pie_sf, height: "200px") %></div>
  <div class="pie-container">UK<%= pie_chart(@supeng_pie_uk, height: "200px") %></div>
  <div class="pie-container">RED<%= pie_chart(@supeng_pie_red, height: "200px") %></div>
</div>

<div style="clear:both">
<%= render partial: "validations" %>
</div>

<% if @board.id == 2 %>
  <div class="alert alert-warning">
    <strong>TL's and projects</strong>
    <% tl_projects.each do |p| %>
      <br />-- <%= p %>
    <% end %>
  </div>
<% end %>

app/views/boards/completed.html.erb
<h1>Completed Projects</h1>

<table class="table table-grid">
<thead>
  <tr>
      <th>Initiative Name</th>
      <th>Project Name</th>
      <th>Dates</th>
      <th>Project Length</th>
      <th>Retro?</th>
  </tr>      
<% @projects.sort{|a,b| b.end_date <=> a.end_date}.each do |p| %>
  <tr>
    <td><%= p.initiative.name %></td>
    <td><%= link_to p.name, edit_board_project_path(@board, p) %></td>
    <td><%= short_date(p.start_date) %> → <%= short_date(p.end_date) %></td>
    <td><%= project_length(p) %> weeks</td>
    <td><%= p.retro? %></td>
<% end %>
  </tr>
</thead>
</table>

app/views/boards/index.html.erb
<% @title = "Boards" %>

<h1>Boards <span><%= link_to 'Create New', new_board_path, :class => 'btn btn-primary btn-xs' %>
</h1>

<ul class="list-unstyled">
<% @boards.each do |board| %>
  <li><h3><%= link_to board.name, board %></h3></li>
<% end %>
</ul>

app/views/boards/new.html.erb
<% @title = "New Board" %>
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<% @title = @board.name %>
<%= render partial: "teams/css", locals: {teams: @board.teams} %>

<div class="row row-board">
<div class="header">
  <h2><%= @board.name %></h2>
  <div class="board-actions pull-right">
    <%= link_to '<span class="glyphicon glyphicon-plus"></span> Create New Project'.html_safe, new_board_project_path(@board), :class => 'btn btn-primary btn-xs' %>
    <%= link_to '<span class="glyphicon glyphicon-pencil"></span> Edit Board'.html_safe, edit_board_path(@board), :class => 'btn btn-default btn-xs' %>
  </div>
</div>
<div class="panel panel-default">
  <div class="table-responsive">
    <table id="board-table" class="table table-condensed table-board">
      <thead>
        <tr>
          <th></th>
          <th class="date">Start Date</th>
          <th class="date">End Date</th>
          <% @board.roles.reverse.each do |r| %>
          <th class="people"><%= r.name %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
      <% @board.ongoing_initiatives.each do |i| %>
        <tr class="initiative active">
          <th colspan="3"><%= link_to i.name, edit_board_initiative_path(@board, i) %></th>
          <td colspan="<%= @board.roles.size %>" class="people">
            <%= person_tag i.manager %><%= person_tag i.owner %><%= person_tag i.analyst %><%= person_tag i.security %>
          </td>
        </tr>
        <% i.ongoing_projects.each do |p| %>
        <tr data-project-id="<%= p.id %>">
          <th class="project <%= " bg-danger" if p.end_date && p.end_date < Date.today %>"><%= link_to p.name, edit_board_project_path(@board, p) %> <sup><%= p.location.name unless p.location.nil? %></sup></th>
          <td class="date<%= " text-danger" if project_length(p) >= 10 %><%= " text-warning" if project_length(p).between?(5,10) %>">
            <% if i.standing? %>

            <% else %>
            <span data-toggle="tooltip" data-placement="bottom" title="<%= num_weeks(p.start_date, p.end_date) %> weeks"><%= p.start_date.strftime("%d %b") unless p.start_date.nil? %></span>
            <% end %>
          </td>
          <td class="date<%= " text-danger" if nearing_deadline p.end_date %>">
            <%= p.end_date.strftime("%d %b") unless p.end_date.nil? %>
          </td>

          <% @board.roles.reverse.each do |r| %>
          <td class="people role-<%= r.name.parameterize %>" data-role-id="<%= r.id %>">
            <ul class="list-inline"><% project_members = p.active_project_members_for_role r.id %>
            <% project_members.each do |pm| %>
              <% week_count = num_weeks(pm.start_date, pm.end_date) %>
              <li class="date"><%= person_tag pm %>
                <div title="<%= week_count %> weeks" class="<%= "text-danger" if project_member_length(pm) >= 10 %><%= "text-warning" if project_member_length(pm).between?(5,10) %>"><%= "#{pm.start_date.strftime("%d %b")} (#{week_count.ceil}w)" if i.standing? && pm.start_date %></div>
            <% end %>
            </ul>
            <% unless !r.limit.nil? && project_members.size >= r.limit %>
            <button class="btn btn-default btn-xs add-person" data-project-id="<%= p.id %>" data-role-id="<%= r.id %>">+ <%= r.name %></button>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
    </div>
  </div>

<%= render partial: "validations" %>
<%= render partial: "project_members/add_modal" %>

<% content_for :javascript do %>
  <script type="text/javascript">

  jQuery(function() {
    window.router = new App.Routers.Boards({
      board: <%= @board.to_json(:include => { 
        :initiatives => {
          :except => [:created_at, :updated_at],
          :include => { 
            :projects => {
              :except => [:created_at, :updated_at],
              :include => {
                :project_members => {
                  :except => [:created_at, :updated_at],
                  :include => {
                    :person => {
                      :only => [:id, :name, :image, :team_id],
                      :include => {
                        :location => { :only => [:name] }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }).html_safe -%>,
      teams: <%= @board.teams.to_json(:except => [:created_at, :updated_at]).html_safe -%>
    });
    Backbone.history.start();
  });
</script>
<% end %>

app/views/boards/todo.html.erb
<h1>Todo </h1>
<h2>The following projects are missing information, would you like to help and complete the information?</h2>
<%= button_to "Send Reminders", :action => :send_reminders, :data => @todo_projects %>
<table class="table table-grid">
<thead>
  <tr>
      <th>Initiative Name</th>
      <th>Project Name</th>
      <th>Missing Fields</th>
  </tr>
	<% @todo_projects.each do |p| %>
  <tr>
    <td><%= p.initiative.name %></td>
    <td><%= link_to p.name, edit_board_project_path(@board, p) %></td>
    <td><% if p.experiment_key == "" || p.experiment_key.nil?  %>
    		<h6> Missing Experiment Key </h6>
    		<% end %>
        <% if p.tech_spec == "" || p.tech_spec.nil? %>
    		<h6> Missing Tech Spec </h6>
    		<% end %>
    </td>
<% end %>
  </tr>
</thead>
</table>