config/routes.rb
Rails.application.routes.draw do

  resources :boards do
    resources :initiatives
    resources :teams
    resources :roles
    resources :projects
    resources :locations
    resources :people do
      collection do
        get :autocomplete
      end
    end
    get 'changelog'
    get 'allocation'
    get 'completed'
    get 'todo'
    post 'send_reminders'
    get 'search', to: 'search#search'
    get 'search/index', to: 'search#index'

  end

  resources :initiatives do
    resources :projects
  end

  resources :projects do
    resources :project_members
  end

  resources :people do
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'home/index'

  get 'sessions/create'

  get '/auth/:provider/callback', to: 'sessions#create'

  authenticated :user do
    devise_scope :user do
      root to: "boards#index"
    end
  end

  unauthenticated do
    devise_scope :user do
      root to: "home#index", :as => "unauthenticated"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title.nil? ? '' : @title + ": " %>Big Board</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :stylesheets %>
</head>
<body>
  <div class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
      <% unless @show_boards_nav %>
        <a class="navbar-brand" href="/">Big Board</a>
      <% else %>
        <%= link_to @board.name, @board, :class => "navbar-brand" %>
      <% end %>
      </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">

          <% if user_signed_in? %>

          <% if @show_boards_nav %>
          <li class="<%= 'active' if params[:action] == 'allocation'  %>"><a href="<%= board_allocation_path(@board) %>">Allocation</a></li>
          <li class="<%= 'active' if params[:action] == 'changelog'  %>"><a href="<%= board_changelog_path(@board) %>">Changelog</a></li>
          <li class="<%= 'active' if params[:action] == 'completed'  %>"><a href="<%= board_completed_path(@board) %>">Completed</a></li>
          <li class="<%= 'active' if params[:action] == 'todo'  %>"><a href="<%= board_todo_path(@board) %>">
          ToDo</a></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="<%= 'active' if params[:controller] == 'initiatives' %>"><a href="<%= board_initiatives_path(@board) %>">Initiatives</a></li>
              <li class="<%= 'active' if params[:controller] == 'teams' %>"><a href="<%= board_teams_path(@board) %>">Teams</a></li>
              <li class="<%= 'active' if params[:controller] == 'roles' %>"><a href="<%= board_roles_path(@board) %>">Roles</a></li>
              <li class="<%= 'active' if params[:controller] == 'people' %>"><a href="<%= board_people_path(@board) %>">People</a></li>
              <li class="<%= 'active' if params[:controller] == 'locations' %>"><a href="<%= board_locations_path(@board) %>">Locations</a></li>
            </ul>
          </li>

          <% end %>

          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in?%>
            <% if @board %>
              <%= form_tag(board_search_path(@board), :method => "get", id: "search-form") do %>
                <%= text_field_tag :query, params[:search], placeholder: "Search project by name or experiment_key", size: 41 %>
              <% end %>
            <% end %>

            <li><a href="/">Boards</a></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
              <li><%= link_to('Logout', destroy_user_session_path) %></li>
              </ul>
            </li>
          <% else %>
            <li><a href="<%= user_omniauth_authorize_path(:yammer) %>">Sign in with Yammer</a></li>
          <% end %>
        </ul>

      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="container<%= "-fluid" if @show_boards_nav && params[:controller] == 'boards'  && params[:action] == "show" %>">
    <div class="row alerts-row">
      <% if !notice.nil? %>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
      <% end %>

      <% if !alert.nil? %>
      <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
      <% end %>
    </div>
<%= yield %>
  </div>
  <footer>
    <div class="container">

    </div>
  </footer>
<script type="text/javascript">
  var ACCESS_TOKEN = "<%= current_user.access_token if user_signed_in? && current_user['access_token'] %>";
</script>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield :javascript %>
</body>
</html>